In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
from tqdm import tqdm

In [3]:
Tickers = [
    "BHP.AX", "CBA.AX", "CSL.AX",
    "NAB.AX", "WBC.AX", "ANZ.AX",
    "WES.AX", "MQG.AX", "WOW.AX", "TLS.AX"
]

In [4]:
testdata = yf.download("BHP.AX", start="2010-01-01")
testdata.head()

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/2671760116.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  testdata = yf.download("BHP.AX", start="2010-01-01")
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker         BHP.AX     BHP.AX     BHP.AX     BHP.AX    BHP.AX
Date
2010-01-04  14.224619  14.284053  14.102448  14.115655   4436014
2010-01-05  14.290658  14.409527  14.274149  14.363300  10918398
2010-01-06  14.468963  14.478869  14.376509  14.389717   7806934
2010-01-07  14.452451  14.574622  14.445847  14.498678   7964069
2010-01-08  14.402929  14.485477  14.363306  14.426041   5510642

In [5]:
single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

print(type(single_df.columns))
print(single_df.columns)
display(single_df.head())

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/3241321429.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

<class 'pandas.core.indexes.multi.MultiIndex'>
MultiIndex([( 'Close', 'BHP.AX'),
            (  'High', 'BHP.AX'),
            (   'Low', 'BHP.AX'),
            (  'Open', 'BHP.AX'),
            ('Volume', 'BHP.AX')],
           names=['Price', 'Ticker'])

Price           Close       High        Low       Open    Volume
Ticker         BHP.AX     BHP.AX     BHP.AX     BHP.AX    BHP.AX
Date
2010-01-04  14.224622  14.284056  14.102451  14.115658   4436014
2010-01-05  14.290660  14.409529  14.274151  14.363302  10918398
2010-01-06  14.468961  14.478867  14.376507  14.389715   7806934
2010-01-07  14.452455  14.574626  14.445851  14.498682   7964069
2010-01-08  14.402925  14.485472  14.363301  14.426037   5510642

In [6]:
single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

if isinstance(single_df.columns, pd.MultiIndex):
    single_df.columns = single_df.columns.get_level_values(0)

single_df = single_df.reset_index()
single_df["Ticker"] = "BHP.AX"

print(single_df.columns)
display(single_df.head())

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/1717547242.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker'], dtype='object', name='Price')

Price       Date      Close       High        Low       Open    Volume  Ticker
0     2010-01-04  14.224617  14.284051  14.102446  14.115653   4436014  BHP.AX
1     2010-01-05  14.290656  14.409525  14.274148  14.363298  10918398  BHP.AX
2     2010-01-06  14.468961  14.478867  14.376507  14.389715   7806934  BHP.AX
3     2010-01-07  14.452451  14.574622  14.445847  14.498678   7964069  BHP.AX
4     2010-01-08  14.402924  14.485471  14.363300  14.426036   5510642  BHP.AX

Up untill now I am just downloading the dataset, but in this dataset the index is multi-index so wi first flattened it

In [7]:
Allstocks = []

for ticker in tqdm(Tickers):
    df = yf.download(ticker, start="2010-01-01", progress=False)

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df = df.reset_index()
    df["Ticker"] = ticker

    Allstocks.append(df)

StocksData = pd.concat(Allstocks, ignore_index=True)

  0%|          | 0/10 [00:00<?, ?it/s]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 10%|█         | 1/10 [00:01<00:11,  1.31s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 20%|██        | 2/10 [00:02<00:10,  1.27s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 30%|███       | 3/10 [00:04<00:11,  1.69s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 40%|████      | 4/10 [00:05<00:09,  1.51s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 50%|█████     | 5/10 [00:07<00:07,  1.42s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 60%|██████    | 6/10 [00:08<00:05,  1.36s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 70%|███████   | 7/10 [00:09<00:04,  1.34s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 80%|████████  | 8/10 [00:11<00:02,  1.31s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 90%|█████████ | 9/10 [00:12<00:01,  1.29s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
100%|██████████| 10/10 [00:13<00:00,  1.33s/it]

In [10]:
print(StocksData.shape)
print(StocksData.columns)
print(StocksData["Ticker"].nunique())
print(StocksData["Ticker"].value_counts())
display(StocksData.head())
display(StocksData.tail())

(41090, 7)
Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker'], dtype='object', name='Price')
10
Ticker
BHP.AX    4109
CBA.AX    4109
CSL.AX    4109
NAB.AX    4109
WBC.AX    4109
ANZ.AX    4109
WES.AX    4109
MQG.AX    4109
WOW.AX    4109
TLS.AX    4109
Name: count, dtype: int64

Price       Date      Close       High        Low       Open    Volume  Ticker
0     2010-01-04  14.224621  14.284055  14.102450  14.115657   4436014  BHP.AX
1     2010-01-05  14.290658  14.409527  14.274149  14.363300  10918398  BHP.AX
2     2010-01-06  14.468966  14.478872  14.376511  14.389720   7806934  BHP.AX
3     2010-01-07  14.452452  14.574623  14.445848  14.498679   7964069  BHP.AX
4     2010-01-08  14.402923  14.485470  14.363299  14.426035   5510642  BHP.AX

Price       Date  Close  High   Low  Open    Volume  Ticker
41085 2026-03-27   5.33  5.33  5.27  5.29  16540034  TLS.AX
41086 2026-03-30   5.34  5.35  5.31  5.31  13070480  TLS.AX
41087 2026-03-31   5.33  5.37  5.32  5.34  20347876  TLS.AX
41088 2026-04-01   5.34  5.34  5.28  5.30  19851741  TLS.AX
41089 2026-04-02   5.42  5.44  5.33  5.33  20877643  TLS.AX

In [11]:
StocksData.describe()

Price,Date,Close,High,Low,Open,Volume
count,41090,41090.000000,41090.000000,41090.000000,41090.000000,4.109000e+04
mean,2018-02-19 00:51:30.971039232,44.281835,44.627409,43.920797,44.285149,7.273220e+06
min,2010-01-04 00:00:00,1.072355,1.076544,1.068166,1.068166,0.000000e+00
25%,2014-01-31 00:00:00,13.877215,13.998548,13.757804,13.885514,1.891888e+06
50%,2018-02-20 00:00:00,20.526177,20.663215,20.385931,20.536034,4.065963e+06
75%,2022-03-10 00:00:00,44.093975,44.376538,43.769523,44.127728,7.673971e+06
max,2026-04-02 00:00:00,311.484406,313.082958,307.858057,310.041202,3.677158e+08
std,NaN,59.270514,59.766718,58.762195,59.288803,1.117329e+07

In [12]:
StocksData.to_csv("data/raw_stocks.csv", index=False)
# this is important as the api might change and reloading them everytime will result in the issue of change in accuracy overtime, 
# i am saving the data locally.

In [13]:
# now because csv dont parse the date time so this might be an issue for me, as the data will be trained in the future project based on 
# rolling window approach so it is really crucial to make sure that the data has the datetime sorted 

FinalStocks = pd.read_csv('data/raw_stocks.csv', parse_dates=["Date"])
# this is the first step to clean the data cleaning and making sure that the date column is of type datetime only

In [14]:
FinalStocks.head(10)

        Date      Close       High        Low       Open    Volume  Ticker
0 2010-01-04  14.224621  14.284055  14.102450  14.115657   4436014  BHP.AX
1 2010-01-05  14.290658  14.409527  14.274149  14.363300  10918398  BHP.AX
2 2010-01-06  14.468966  14.478872  14.376511  14.389720   7806934  BHP.AX
3 2010-01-07  14.452452  14.574623  14.445848  14.498679   7964069  BHP.AX
4 2010-01-08  14.402923  14.485470  14.363299  14.426035   5510642  BHP.AX
5 2010-01-11  14.683585  14.690189  14.505282  14.521792  11048942  BHP.AX
6 2010-01-12  14.359999  14.495377  14.343489  14.478868  10769158  BHP.AX
7 2010-01-13  14.237831  14.277455  14.151982  14.181699  15675825  BHP.AX
8 2010-01-14  14.455756  14.544909  14.317077  14.346793  12295931  BHP.AX
9 2010-01-15  14.412827  14.422733  14.290656  14.386412  16956523  BHP.AX