In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
from tqdm import tqdm

In [3]:
Tickers = [
    "BHP.AX", "CBA.AX", "CSL.AX",
    "NAB.AX", "WBC.AX", "ANZ.AX",
    "WES.AX", "MQG.AX", "WOW.AX", "TLS.AX"
]

In [4]:
testdata = yf.download("BHP.AX", start="2010-01-01")
testdata.head()

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/2671760116.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  testdata = yf.download("BHP.AX", start="2010-01-01")
[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker         BHP.AX     BHP.AX     BHP.AX     BHP.AX    BHP.AX
Date
2010-01-04  14.224619  14.284053  14.102448  14.115655   4436014
2010-01-05  14.290658  14.409527  14.274149  14.363300  10918398
2010-01-06  14.468963  14.478869  14.376509  14.389717   7806934
2010-01-07  14.452451  14.574622  14.445847  14.498678   7964069
2010-01-08  14.402929  14.485477  14.363306  14.426041   5510642

In [5]:
single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

print(type(single_df.columns))
print(single_df.columns)
display(single_df.head())

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/3241321429.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

<class 'pandas.core.indexes.multi.MultiIndex'>
MultiIndex([( 'Close', 'BHP.AX'),
            (  'High', 'BHP.AX'),
            (   'Low', 'BHP.AX'),
            (  'Open', 'BHP.AX'),
            ('Volume', 'BHP.AX')],
           names=['Price', 'Ticker'])

Price           Close       High        Low       Open    Volume
Ticker         BHP.AX     BHP.AX     BHP.AX     BHP.AX    BHP.AX
Date
2010-01-04  14.224622  14.284056  14.102451  14.115658   4436014
2010-01-05  14.290660  14.409529  14.274151  14.363302  10918398
2010-01-06  14.468961  14.478867  14.376507  14.389715   7806934
2010-01-07  14.452455  14.574626  14.445851  14.498682   7964069
2010-01-08  14.402925  14.485472  14.363301  14.426037   5510642

In [6]:
single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

if isinstance(single_df.columns, pd.MultiIndex):
    single_df.columns = single_df.columns.get_level_values(0)

single_df = single_df.reset_index()
single_df["Ticker"] = "BHP.AX"

print(single_df.columns)
display(single_df.head())

/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/1717547242.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  single_df = yf.download("BHP.AX", start="2010-01-01", progress=False)

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker'], dtype='object', name='Price')

Price       Date      Close       High        Low       Open    Volume  Ticker
0     2010-01-04  14.224617  14.284051  14.102446  14.115653   4436014  BHP.AX
1     2010-01-05  14.290656  14.409525  14.274148  14.363298  10918398  BHP.AX
2     2010-01-06  14.468961  14.478867  14.376507  14.389715   7806934  BHP.AX
3     2010-01-07  14.452451  14.574622  14.445847  14.498678   7964069  BHP.AX
4     2010-01-08  14.402924  14.485471  14.363300  14.426036   5510642  BHP.AX

Up untill now I am just downloading the dataset, but in this dataset the index is multi-index so wi first flattened it

In [7]:
Allstocks = []

for ticker in tqdm(Tickers):
    df = yf.download(ticker, start="2010-01-01", progress=False)

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df = df.reset_index()
    df["Ticker"] = ticker

    Allstocks.append(df)

StocksData = pd.concat(Allstocks, ignore_index=True)

  0%|          | 0/10 [00:00<?, ?it/s]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 10%|█         | 1/10 [00:01<00:11,  1.31s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 20%|██        | 2/10 [00:02<00:10,  1.27s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 30%|███       | 3/10 [00:04<00:11,  1.69s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 40%|████      | 4/10 [00:05<00:09,  1.51s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 50%|█████     | 5/10 [00:07<00:07,  1.42s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 60%|██████    | 6/10 [00:08<00:05,  1.36s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 70%|███████   | 7/10 [00:09<00:04,  1.34s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 80%|████████  | 8/10 [00:11<00:02,  1.31s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
 90%|█████████ | 9/10 [00:12<00:01,  1.29s/it]/var/folders/5l/hdkvhlj11x73wsv279bv3wfh0000gn/T/ipykernel_20795/4232886398.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2010-01-01", progress=False)
100%|██████████| 10/10 [00:13<00:00,  1.33s/it]

In [10]:
print(StocksData.shape)
print(StocksData.columns)
print(StocksData["Ticker"].nunique())
print(StocksData["Ticker"].value_counts())
display(StocksData.head())
display(StocksData.tail())

(41090, 7)
Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker'], dtype='object', name='Price')
10
Ticker
BHP.AX    4109
CBA.AX    4109
CSL.AX    4109
NAB.AX    4109
WBC.AX    4109
ANZ.AX    4109
WES.AX    4109
MQG.AX    4109
WOW.AX    4109
TLS.AX    4109
Name: count, dtype: int64

Price       Date      Close       High        Low       Open    Volume  Ticker
0     2010-01-04  14.224621  14.284055  14.102450  14.115657   4436014  BHP.AX
1     2010-01-05  14.290658  14.409527  14.274149  14.363300  10918398  BHP.AX
2     2010-01-06  14.468966  14.478872  14.376511  14.389720   7806934  BHP.AX
3     2010-01-07  14.452452  14.574623  14.445848  14.498679   7964069  BHP.AX
4     2010-01-08  14.402923  14.485470  14.363299  14.426035   5510642  BHP.AX

Price       Date  Close  High   Low  Open    Volume  Ticker
41085 2026-03-27   5.33  5.33  5.27  5.29  16540034  TLS.AX
41086 2026-03-30   5.34  5.35  5.31  5.31  13070480  TLS.AX
41087 2026-03-31   5.33  5.37  5.32  5.34  20347876  TLS.AX
41088 2026-04-01   5.34  5.34  5.28  5.30  19851741  TLS.AX
41089 2026-04-02   5.42  5.44  5.33  5.33  20877643  TLS.AX

In [11]:
StocksData.describe()

Price,Date,Close,High,Low,Open,Volume
count,41090,41090.000000,41090.000000,41090.000000,41090.000000,4.109000e+04
mean,2018-02-19 00:51:30.971039232,44.281835,44.627409,43.920797,44.285149,7.273220e+06
min,2010-01-04 00:00:00,1.072355,1.076544,1.068166,1.068166,0.000000e+00
25%,2014-01-31 00:00:00,13.877215,13.998548,13.757804,13.885514,1.891888e+06
50%,2018-02-20 00:00:00,20.526177,20.663215,20.385931,20.536034,4.065963e+06
75%,2022-03-10 00:00:00,44.093975,44.376538,43.769523,44.127728,7.673971e+06
max,2026-04-02 00:00:00,311.484406,313.082958,307.858057,310.041202,3.677158e+08
std,NaN,59.270514,59.766718,58.762195,59.288803,1.117329e+07

In [12]:
StocksData.to_csv("data/raw_stocks.csv", index=False)
# this is important as the api might change and reloading them everytime will result in the issue of change in accuracy overtime, 
# i am saving the data locally.

In [13]:
# now because csv dont parse the date time so this might be an issue for me, as the data will be trained in the future project based on 
# rolling window approach so it is really crucial to make sure that the data has the datetime sorted 

FinalStocks = pd.read_csv('data/raw_stocks.csv', parse_dates=["Date"])
# this is the first step to clean the data cleaning and making sure that the date column is of type datetime only

In [14]:
FinalStocks.head(10)

        Date      Close       High        Low       Open    Volume  Ticker
0 2010-01-04  14.224621  14.284055  14.102450  14.115657   4436014  BHP.AX
1 2010-01-05  14.290658  14.409527  14.274149  14.363300  10918398  BHP.AX
2 2010-01-06  14.468966  14.478872  14.376511  14.389720   7806934  BHP.AX
3 2010-01-07  14.452452  14.574623  14.445848  14.498679   7964069  BHP.AX
4 2010-01-08  14.402923  14.485470  14.363299  14.426035   5510642  BHP.AX
5 2010-01-11  14.683585  14.690189  14.505282  14.521792  11048942  BHP.AX
6 2010-01-12  14.359999  14.495377  14.343489  14.478868  10769158  BHP.AX
7 2010-01-13  14.237831  14.277455  14.151982  14.181699  15675825  BHP.AX
8 2010-01-14  14.455756  14.544909  14.317077  14.346793  12295931  BHP.AX
9 2010-01-15  14.412827  14.422733  14.290656  14.386412  16956523  BHP.AX

In [16]:
# Now lets start with Data cleaning, PreProcessing and EDA

FinalStocks.shape

(41090, 7)

In [17]:
FinalStocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41090 entries, 0 to 41089
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    41090 non-null  datetime64[ns]
 1   Close   41090 non-null  float64
 2   High    41090 non-null  float64
 3   Low     41090 non-null  float64
 4   Open    41090 non-null  float64
 5   Volume  41090 non-null  int64
 6   Ticker  41090 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 2.2+ MB

In [22]:
FinalStocks.isnull().sum()
#No null values, which means data for the full 16 years is present, for every stock out of the 10 stocks i chose

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
Ticker    0
dtype: int64

In [26]:
summary = FinalStocks.groupby("Ticker").agg({
    "Date": ["min", "max", "count"]
})

summary.columns = ["Start_Date", "End_Date", "Num_Records"]

print(summary)
# this is done to check what is start data for every ticker and what data will be present, basically looking for any anomaly

       Start_Date   End_Date  Num_Records
Ticker
ANZ.AX 2010-01-04 2026-04-02         4109
BHP.AX 2010-01-04 2026-04-02         4109
CBA.AX 2010-01-04 2026-04-02         4109
CSL.AX 2010-01-04 2026-04-02         4109
MQG.AX 2010-01-04 2026-04-02         4109
NAB.AX 2010-01-04 2026-04-02         4109
TLS.AX 2010-01-04 2026-04-02         4109
WBC.AX 2010-01-04 2026-04-02         4109
WES.AX 2010-01-04 2026-04-02         4109
WOW.AX 2010-01-04 2026-04-02         4109

In [27]:
is_sorted = FinalStocks.groupby("Ticker")["Date"].apply(lambda x: x.is_monotonic_increasing)

print(is_sorted)

Ticker
ANZ.AX    True
BHP.AX    True
CBA.AX    True
CSL.AX    True
MQG.AX    True
NAB.AX    True
TLS.AX    True
WBC.AX    True
WES.AX    True
WOW.AX    True
Name: Date, dtype: bool

In [31]:
FinalStocks['Return'] = FinalStocks.groupby("Ticker")["Close"].pct_change()

In [32]:
FinalStocks.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,Return
0,2010-01-04,14.224621,14.284055,14.102450,14.115657,4436014,BHP.AX,NaN
1,2010-01-05,14.290658,14.409527,14.274149,14.363300,10918398,BHP.AX,0.004642
2,2010-01-06,14.468966,14.478872,14.376511,14.389720,7806934,BHP.AX,0.012477
3,2010-01-07,14.452452,14.574623,14.445848,14.498679,7964069,BHP.AX,-0.001141
4,2010-01-08,14.402923,14.485470,14.363299,14.426035,5510642,BHP.AX,-0.003427
5,2010-01-11,14.683585,14.690189,14.505282,14.521792,11048942,BHP.AX,0.019486
6,2010-01-12,14.359999,14.495377,14.343489,14.478868,10769158,BHP.AX,-0.022037
7,2010-01-13,14.237831,14.277455,14.151982,14.181699,15675825,BHP.AX,-0.008507
8,2010-01-14,14.455756,14.544909,14.317077,14.346793,12295931,BHP.AX,0.015306
9,2010-01-15,14.412827,14.422733,14.290656,14.386412,16956523,BHP.AX,-0.002970

In [34]:
FinalStocks["LogReturn"] = FinalStocks.groupby("Ticker")["Close"].transform(lambda x: np.log(x / x.shift(1)))

In [35]:
FinalStocks.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,Return,LogReturn
0,2010-01-04,14.224621,14.284055,14.102450,14.115657,4436014,BHP.AX,NaN,NaN
1,2010-01-05,14.290658,14.409527,14.274149,14.363300,10918398,BHP.AX,0.004642,0.004632
2,2010-01-06,14.468966,14.478872,14.376511,14.389720,7806934,BHP.AX,0.012477,0.012400
3,2010-01-07,14.452452,14.574623,14.445848,14.498679,7964069,BHP.AX,-0.001141,-0.001142
4,2010-01-08,14.402923,14.485470,14.363299,14.426035,5510642,BHP.AX,-0.003427,-0.003433
5,2010-01-11,14.683585,14.690189,14.505282,14.521792,11048942,BHP.AX,0.019486,0.019299
6,2010-01-12,14.359999,14.495377,14.343489,14.478868,10769158,BHP.AX,-0.022037,-0.022284
7,2010-01-13,14.237831,14.277455,14.151982,14.181699,15675825,BHP.AX,-0.008507,-0.008544
8,2010-01-14,14.455756,14.544909,14.317077,14.346793,12295931,BHP.AX,0.015306,0.015190
9,2010-01-15,14.412827,14.422733,14.290656,14.386412,16956523,BHP.AX,-0.002970,-0.002974

Now i have got the return columns which is really crucial in order to check what will the whole trend will be.

Further more i am adding Technical Indicators which are required for the model to predict as the model cannot see charts but it can see differnt deviation and numbers on the basis of which it can learn how to make sure that the trend is moving

* **SMA** - Simple Moving Average: to predict the upward or the downward trend of the stock
* **Volatility**: To predict the risk and uncertainity of a stock

In [37]:
FinalStocks["SMA_5"] = FinalStocks.groupby("Ticker")["Close"].transform(lambda x: x.rolling(window=5).mean())
FinalStocks["SMA_10"] = FinalStocks.groupby("Ticker")["Close"].transform(lambda x: x.rolling(window=10).mean())
FinalStocks["VOLATILE_5"] = FinalStocks.groupby("Ticker")["Close"].transform(lambda x: x.rolling(window=5).std())
FinalStocks["VOLATILE_10"] = FinalStocks.groupby("Ticker")["Close"].transform(lambda x: x.rolling(window=10).std())

In [38]:
FinalStocks.head(15)

,Date,Close,High,Low,Open,Volume,Ticker,Return,LogReturn,SMA_5,SMA_10,VOLATILE_5,VOLATILE_10
0,2010-01-04,14.224621,14.284055,14.102450,14.115657,4436014,BHP.AX,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,14.290658,14.409527,14.274149,14.363300,10918398,BHP.AX,0.004642,0.004632,NaN,NaN,NaN,NaN
2,2010-01-06,14.468966,14.478872,14.376511,14.389720,7806934,BHP.AX,0.012477,0.012400,NaN,NaN,NaN,NaN
3,2010-01-07,14.452452,14.574623,14.445848,14.498679,7964069,BHP.AX,-0.001141,-0.001142,NaN,NaN,NaN,NaN
4,2010-01-08,14.402923,14.485470,14.363299,14.426035,5510642,BHP.AX,-0.003427,-0.003433,14.367924,NaN,0.106166,NaN
5,2010-01-11,14.683585,14.690189,14.505282,14.521792,11048942,BHP.AX,0.019486,0.019299,14.459717,NaN,0.143232,NaN
6,2010-01-12,14.359999,14.495377,14.343489,14.478868,10769158,BHP.AX,-0.022037,-0.022284,14.473585,NaN,0.124963,NaN
7,2010-01-13,14.237831,14.277455,14.151982,14.181699,15675825,BHP.AX,-0.008507,-0.008544,14.427358,NaN,0.163812,NaN
8,2010-01-14,14.455756,14.544909,14.317077,14.346793,12295931,BHP.AX,0.015306,0.015190,14.428019,NaN,0.163945,NaN
9,2010-01-15,14.412827,14.422733,14.290656,14.386412,16956523,BHP.AX,-0.002970,-0.002974,14.430000,14.398962,0.163625,0.134086
10,2010-01-18,14.343487,14.353393,14.188297,14.227921,14933201,BHP.AX,-0.004811,-0.004823,14.361980,14.410848,0.082369,0.121601
11,2010-01-19,14.300568,14.465664,14.300568,14.409532,16769171,BHP.AX,-0.002992,-0.002997,14.350094,14.411839,0.086890,0.120549
12,2010-01-20,14.333583,14.508584,14.330281,14.462357,15383620,BHP.AX,0.002309,0.002306,14.369244,14.398301,0.063316,0.121021
13,2010-01-21,14.089244,14.221319,14.082639,14.181696,17785914,BHP.AX,-0.017047,-0.017194,14.295942,14.361980,0.122561,0.153191
14,2010-01-22,13.768955,13.768955,13.617067,13.676503,21740426,BHP.AX,-0.022733,-0.022995,14.167167,14.298584,0.245572,0.240605

In [39]:
FinalStocks["TargetReturn"] = FinalStocks.groupby("Ticker")["Return"].transform(
    lambda x: x.shift(-1)
)

In [40]:
display(FinalStocks[["Date", "Ticker", "Return", "TargetReturn"]].head(10))

        Date  Ticker    Return  TargetReturn
0 2010-01-04  BHP.AX       NaN      0.004642
1 2010-01-05  BHP.AX  0.004642      0.012477
2 2010-01-06  BHP.AX  0.012477     -0.001141
3 2010-01-07  BHP.AX -0.001141     -0.003427
4 2010-01-08  BHP.AX -0.003427      0.019486
5 2010-01-11  BHP.AX  0.019486     -0.022037
6 2010-01-12  BHP.AX -0.022037     -0.008507
7 2010-01-13  BHP.AX -0.008507      0.015306
8 2010-01-14  BHP.AX  0.015306     -0.002970
9 2010-01-15  BHP.AX -0.002970     -0.004811

In [41]:
display(FinalStocks[["Date", "Ticker", "Return", "TargetReturn"]].tail(10))

            Date  Ticker    Return  TargetReturn
41080 2026-03-20  TLS.AX -0.001887      0.001890
41081 2026-03-23  TLS.AX  0.001890      0.007547
41082 2026-03-24  TLS.AX  0.007547     -0.003745
41083 2026-03-25  TLS.AX -0.003745     -0.001880
41084 2026-03-26  TLS.AX -0.001880      0.003766
41085 2026-03-27  TLS.AX  0.003766      0.001876
41086 2026-03-30  TLS.AX  0.001876     -0.001873
41087 2026-03-31  TLS.AX -0.001873      0.001876
41088 2026-04-01  TLS.AX  0.001876      0.014981
41089 2026-04-02  TLS.AX  0.014981           NaN

Now with this feature we are planning to give the target to the model, which is the next day, if todays return is X what will be tommorows return to predict which is lets say Y

now here the ``TargetReturn`` is the regression target and ``TargetTrend`` is classification target

In [42]:
FinalStocks["TargetTrend"] =(FinalStocks["TargetReturn"] > 0).astype(int)

In [43]:
FinalStocks.head(10)

,Date,Close,High,Low,Open,Volume,Ticker,Return,LogReturn,SMA_5,SMA_10,VOLATILE_5,VOLATILE_10,TargetReturn,TargetTrend
0,2010-01-04,14.224621,14.284055,14.102450,14.115657,4436014,BHP.AX,NaN,NaN,NaN,NaN,NaN,NaN,0.004642,1
1,2010-01-05,14.290658,14.409527,14.274149,14.363300,10918398,BHP.AX,0.004642,0.004632,NaN,NaN,NaN,NaN,0.012477,1
2,2010-01-06,14.468966,14.478872,14.376511,14.389720,7806934,BHP.AX,0.012477,0.012400,NaN,NaN,NaN,NaN,-0.001141,0
3,2010-01-07,14.452452,14.574623,14.445848,14.498679,7964069,BHP.AX,-0.001141,-0.001142,NaN,NaN,NaN,NaN,-0.003427,0
4,2010-01-08,14.402923,14.485470,14.363299,14.426035,5510642,BHP.AX,-0.003427,-0.003433,14.367924,NaN,0.106166,NaN,0.019486,1
5,2010-01-11,14.683585,14.690189,14.505282,14.521792,11048942,BHP.AX,0.019486,0.019299,14.459717,NaN,0.143232,NaN,-0.022037,0
6,2010-01-12,14.359999,14.495377,14.343489,14.478868,10769158,BHP.AX,-0.022037,-0.022284,14.473585,NaN,0.124963,NaN,-0.008507,0
7,2010-01-13,14.237831,14.277455,14.151982,14.181699,15675825,BHP.AX,-0.008507,-0.008544,14.427358,NaN,0.163812,NaN,0.015306,1
8,2010-01-14,14.455756,14.544909,14.317077,14.346793,12295931,BHP.AX,0.015306,0.015190,14.428019,NaN,0.163945,NaN,-0.002970,0
9,2010-01-15,14.412827,14.422733,14.290656,14.386412,16956523,BHP.AX,-0.002970,-0.002974,14.430000,14.398962,0.163625,0.134086,-0.004811,0

So now lets clarify what I am planning to do here, this is the universal dataset which I am making this data will be loaded into the ML models for time t to predict t+1 then this will be loaded into the LSTM with rolling window concept of 30 days to predict next day, after which I will add the macro economic data along with the sentiment into my core Hybrid Model.